//package com.tap.Test;
//
//
//import com.tap.DaoImple.RestaurantImp;
//import com.tap.modeal.Restaurant;
//
//import java.util.ArrayList;
//
//public class Test2 {
//    public static void main(String[] args) {
//
//        RestaurantImp dao = new RestaurantImp();
//
//        // 1. Add a new restaurant
//        Restaurant newRestaurant = new Restaurant(
//                0, // ID will be auto-generated by DB
//                "Pizza Palace",
//                "images/pizza.jpg",
//                5,
//                "30 mins",
//                "Italian",
//                "123 Pizza Street, Food City",
//                true,
//                "owner123"
//        );
//
//        dao.addRestaurant(newRestaurant);
//        System.out.println("Restaurant added successfully.\n");
//
//        // 2. Get a restaurant by ID (change ID to one that exists)
//        Restaurant fetched = dao.getRestaurant(1);
//        if (fetched != null) {
//            System.out.println("Fetched Restaurant:");
//            System.out.println("Name: " + fetched.getName());
//            System.out.println("Cuisine: " + fetched.getCuisineType());
//        } else {
//            System.out.println("No restaurant found with that ID.\n");
//        }
//
//        // 3. Update restaurant (use fetched one and modify)
//        if (fetched != null) {
//            fetched.setName("Updated Pizza Palace");
//            fetched.setEta("25 mins");
//            dao.updateRestaurant(fetched);
//            System.out.println("Restaurant updated successfully.\n");
//        }
//
//        // 4. Get all restaurants
//        ArrayList<Restaurant> allRestaurants = dao.getAllRestaurant();
//        System.out.println("All Restaurants:");
//        for (Restaurant r : allRestaurants) {
//            System.out.println(r.getRestaurantId() + ": " + r.getName() + " (" + r.getCuisineType() + ")");
//        }
//
//        // 5. Delete a restaurant by ID (optional)
//        dao.deleteRestaurant(1); // change to a real ID if needed
//        System.out.println("Restaurant deleted (if ID existed).\n");
//    }
//}
